apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 80  # Port on which your web application listens inside the pods
      targetPort: 80  # Port on which your web application listens in the container
  type: LoadBalancer  # Change to NodePort or ClusterIP if you don't have a cloud provider
